/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example


class Coche(private var _marca: String = "Ford", private var _modelo: Int = 2020) {
    var marca: String
        get() = _marca
        set(value) {
            _marca = value
        }
    var modelo: Int
        get() = _modelo
        set(value) {
            _modelo = value
        }
}

// Escribir una interface perimetrable con un metodo calcularPerimetro()
    // Escribir una clase Rectangulo que implemente la interface Perimetrable
    // Escribir una clase Circulo que implemente la interface Perimetrable
    // Crear una lista con un objeto de cada clase y mostrar el perimetro de cada uno

interface Perimetrable {
    fun calcularPerimetro(): Double
    val nombre: String
}

class Rectangulo(override val nombre: String, val ancho: Int, val alto: Int) : Perimetrable {
    override fun calcularPerimetro(): Double {
        return 2.0 * (ancho + alto)
    }
}

class Circulo(override val nombre: String, val radio: Double) : Perimetrable {
    override fun calcularPerimetro(): Double {
        return 2 * Math.PI * radio
    }
}

fun main() {

    val coche = Coche("Chevrolet", 2025)

    println("Marca ${coche.marca}")
    println("Modelo ${coche.modelo}")

    val rectangulo = Rectangulo("Rectangulo",6, 8)
    val circulo = Circulo("Circulo",0.5)

    val figuras: List<Perimetrable> = listOf(rectangulo, circulo)

    figuras.forEach { figura ->
        println("El perímetro del ${figura.nombre}: ${figura.calcularPerimetro()}")
    }

}